name: Host Service CI

on:
  push:
    branches: ["main"]
    paths: ["*.js"]


jobs:

  buildImage:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Ckeckout
      uses: actions/checkout@v3
    - name: 2. Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: 3. Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: kozyaura/hostservice:${{ github.sha }}
  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage
    steps: 
    - name: 1. Checkout
      uses: actions/checkout@v3
      with:
        repository: "bee2947762/hostsvc-cd"
        token: ${{ secrets.KOZY_TOKEN }}
    - name: 2. Change Docker Tag
      run: |
        sed -i "s/image: kozyaura\/node-app:.*/images: kozyaura\/node-app:${{ github.sha }}/g" hostservice-deploy.yaml
        git config --global user.email "bee2947762@gmail.com"
        git config --global user.name "bee2947762"
        git commit -am "triggered by github action"
        git push origin main